version: '3.3'

services:
   db:
     image: webhippie/mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
       - /root/db_backup:/backup
     restart: always
     container_name: wordpress-db
     environment:
       MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MARIADB_DATABASE: ${DB_NAME}
       MARIADB_USERNAME: ${DB_USERNAME}
       MARIADB_PASSWORD: ${DB_PASSWORD}
       MARIADB_MAX_ALLOWED_PACKET: 128M
       MARIADB_INNODB_LOG_FILE_SIZE: 64M

   wordpress:
     depends_on:
       - db
     image: patklaey/wordpress:5.8.0
     volumes:
       - /home/blog-uploads:/var/www/html/wp-content/uploads
     ports:
       - "8000:80"
     restart: always
     container_name: wordpress-web
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${DB_USERNAME}
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
       WORDPRESS_DB_NAME: ${DB_NAME}
volumes:
    db_data: {}
