version: '3.3'

services:
   db:
     image: webhippie/mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
       - /root/db_backup:/backup
     restart: always
     container_name: wordpress-db
     environment:
       MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MARIADB_DATABASE: ${DB_NAME}
       MARIADB_USERNAME: ${DB_USERNAME}
       MARIADB_PASSWORD: ${DB_PASSWORD}
       MARIADB_MAX_ALLOWED_PACKET: 128M
       MARIADB_INNODB_LOG_FILE_SIZE: 64M

   wordpress:
     depends_on:
       - db
     image: patklaey/wordpress:5.9.0-2
     volumes:
       - /home/blog-uploads:/var/www/html/wp-content/uploads
     ports:
       - "8000:80"
     restart: always
     container_name: wordpress-web
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${DB_USERNAME}
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
       WORDPRESS_DB_NAME: ${DB_NAME}
       WORDPRESS_SMTP_HOST: ${WORDPRESS_SMTP_HOST}
       WORDPRESS_SMTP_PORT: ${WORDPRESS_SMTP_PORT}
       WORDPRESS_SMTP_USERNAME: ${WORDPRESS_SMTP_USERNAME}
       WORDPRESS_SMTP_PASSWORD: ${WORDPRESS_SMTP_PASSWORD}
       WORDPRESS_SMTP_FROM: ${WORDPRESS_SMTP_FROM}
       WORDPRESS_SMTP_FROM_NAME: ${WORDPRESS_SMTP_FROM_NAME}
       WORDPRESS_CONFIG_EXTRA: |
          // SMTP Settings
          require_once( ABSPATH .'wp-includes/plugin.php' );
          add_action( 'phpmailer_init', 'mail_smtp' );
          function mail_smtp( $$phpmailer ) {
              $$phpmailer->isSMTP();
              $$phpmailer->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
              $$phpmailer->Host = getenv('WORDPRESS_SMTP_HOST');
              $$phpmailer->Port = getenv('WORDPRESS_SMTP_PORT');
              $$phpmailer->Username = getenv('WORDPRESS_SMTP_USERNAME');
              $$phpmailer->Password = getenv('WORDPRESS_SMTP_PASSWORD');
              $$phpmailer->SetFrom(getenv('WORDPRESS_SMTP_FROM'), getenv('WORDPRESS_SMTP_FROM_NAME'));

              // Additional settings
              $$phpmailer->SMTPAuth = true;

              // Filter out client message body and output debug info to the logs
              // NOTE: Log level must be set to '2' or higher in order for the filter to work
              $$phpmailer->SMTPDebug = 2;

              $$phpmailer->Debugoutput = function($$str) {
                  static $$logging = true;
                  if ($$logging === false && strpos($$str, 'SERVER -> CLIENT') !== false) {
                      $$logging = true;
                  }
                  if ($$logging) {
                      error_log("SMTP " . "$$str");
                  }
                  if (strpos($$str, 'SERVER -> CLIENT: 354') !== false) {
                      $$logging = false;
                  }
              };
          }
          add_filter( 'wp_mail', function( $$mailArray ) {
            global $$phpmailer;
            if ( ! ( $$phpmailer instanceof PHPMailer ) ) {
                require_once ABSPATH . WPINC . '/class-phpmailer.php';
                require_once ABSPATH . WPINC . '/class-smtp.php';
                $$phpmailer = new PHPMailer( true );
            }
            $$phpmailer::$$validator = 'noregex';
            return $$mailArray;
          } );
          // Prevent Wordpress from overriding the SMTP FROM address (Office 365 compatibility)
          add_filter( 'wp_mail_from', function( $$email ) {
              return getenv('WORDPRESS_SMTP_FROM');
          });
          add_action('wp_mail_failed', function( $$wperror ) {
                  error_log(implode("; ", $$wperror->get_error_messages()));
          });
volumes:
    db_data: {}
