version: '3.3'

services:
   db:
     image: patklaey/mysql:5.5
     volumes:
       - db_data:/var/lib/mysql
       - /root/db_backup:/backup
     restart: always
     container_name: wordpress-db
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DB_NAME}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - db
     image: patklaey/wordpress:5.2.4
     volumes:
       - /home/blog-uploads:/var/www/html/wp-content/uploads
     ports:
       - "8000:80"
     restart: always
     container_name: wordpress-web
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
volumes:
    db_data: {}
